### ISSUE TITLE
Input devices

### ISSUE THREAD

**Issue by chris1234a** [chris1234a/robot_ws#11]
- Need drivers for more input devices. Currently `wiimote_driver` is only available.

- Which devices? PS3/4 remote? Logitech remote? Joystick? Keyboard? Mouse?

- I'm considering getting one of [these](https://www.myo.com/), a driver/interface could be written using [this](http://www.fernandocosentino.net/pyoconnect/).

- @cam586 any ideas?

**Comment by cam586** [comment]
I suppose if the drivers are easy to write we could add a few. I think I will also consider writing one for bluetooth connection for android - phones are quite ubiquitous! Keyboard should be simple, just might need to get used to threading. 

I think ps3/ps4 would be a good starting point for actual controllers - we both have them readily available. Let's start there!

**Comment by chris1234a** [comment]
Now in projects.
