### ISSUE TITLE
RGB-D sensors and Octomap for robot_ws

### ISSUE THREAD

**Issue by chris1234a** [chris1234a/robot_ws#12]
See [here](https://www.youtube.com/watch?v=DMXKp98BY-w) and [here](https://octomap.github.io). This might be a challenge but if it worked would be awesome!

@cam586 what do you think?

**Comment by cam586** [comment]
Wow, I assumed it would be way too resource intensive to get pointclouds/Octomaps working on the pi - definitely worth a try!

**Comment by chris1234a** [comment]
This is now in projects.
