### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chris1234a** [chris1234a/robot_ws#7]
Probably a good idea to start thinking about documentation.

**Comment by chris1234a** [comment]
Document in wiki? Then write up in LaTeX in a dir called `docs`?

**Comment by cam586** [comment]
Popped a few quick placeholders in the wiki, basically a segmented copy and paste of the readme file

**Comment by chris1234a** [comment]
@cam586 looks good!

**Comment by chris1234a** [comment]
Now in projects.
