### ISSUE TITLE
Platform independence

### ISSUE THREAD

**Issue by chris1234a** [chris1234a/robot_ws#9]
This is to think about in the long term.

I'd like this workspace to be platform independent, i.e. can be deployed on any raspberry pi robot and will work out the box given some minor setup from the user.  I'm going to get one of [this](https://www.youtube.com/watch?v=4BB2CVRVU50) and [this](https://www.youtube.com/watch?v=O0-Q5N5SAMI). Unfortunately, the guys who made these designed it for the Arduino but I think it shouldn't be too much work to get it to run using a RPi.

List here any ideas for drivers/modules that would need to be developed and any platform independence issues that may be something to think about.

**Comment by cam586** [comment]
That's a good idea and having two separate systems ourselves and getting the two extra that you mentioned will make this a necessity and relatively simple to test.

Any periphery that is handled directly by the GPIO pins would be no problem to integrate, however anything that uses an intermediary, like a motor board may present issues as they can vary hugely in their setup. It may be possible to do easily, with some basic setup (as you said), but may still need a fair amount of testing!

Definitely something we should with towards though

On 26 Mar 2017 6:53 p.m., "Chris Mower" <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #9<https://github.com/chris1234a/robot_ws/issues/9> to @cam586<https://github.com/cam586>.

**Comment by chris1234a** [comment]
This is now in projects.
